<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0);?>
<tables>
	<field>
		<name>id</name>
		<primarykey>1</primarykey>
		<extra>autoincrement</extra>
		<frm_show>0</frm_show>
	</field>
	<field>
		<name>enabled</name>
		<type>radio</type>
		<frm_i18n>enabled</frm_i18n>
		<frm_options>0,1</frm_options>
		<frm_options_i18n>no,yes</frm_options_i18n>
		<frm_default>1</frm_default>
	</field>
	<field>
		<name>optional</name>
		<type>radio</type>
		<frm_i18n>optional</frm_i18n>
		<frm_options>0,1</frm_options>
		<frm_options_i18n>no,yes</frm_options_i18n>
		<frm_default>0</frm_default>
	</field>
	<field>
		<name>title</name>
		<frm_i18n>title</frm_i18n>
		<type>varchar</type>
		<frm_multilanguages>auto</frm_multilanguages>
	</field>
	<field>
		<name>text</name>
		<type>text</type>
		<frm_i18n>text</frm_i18n>
		<frm_required>1</frm_required>
		<frm_cols>60</frm_cols>
		<frm_multilanguages>auto</frm_multilanguages>
		<frm_type>html</frm_type>		
	</field>
	<field>
		<name>text_it</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
	<field>
		<name>text_en</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
	<field>
		<name>text_fr</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>	
	<field>
		<name>position</name>
	</field>
	<filename>conditions</filename>
</tables>