<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0); ?>
<tables>
    <field>
        <name>id</name>
        <type>int</type>
        <primarykey>1</primarykey>
        <extra>autoincrement</extra>
    </field>
    <field>
        <name>context</name>
        <type>varchar</type>
    </field>
    <field>
        <name>event</name>
        <type>text</type>
    </field>
    <field>
        <name>ip</name>
        <type>varchar</type>
    </field>
    <field>
        <name>user</name>
        <type>varchar</type>
    </field>
    <field>
        <name>date</name>
        <type>datetime</type>
    </field>
    <indexfield>context</indexfield>
    <filename>logs</filename>
</tables>