<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0);?>
<fn_sections>
	<type>news</type>
	<parent></parent>
	<position>50</position>
	<title>News</title>
	<description></description>
	<startdate></startdate>
	<enddate></enddate>
	<status>1</status>
	<hidden>0</hidden>
	<accesskey></accesskey>
	<keywords></keywords>
	<sectionpath>sections</sectionpath>
	<level></level>
	<group_view></group_view>
	<group_edit></group_edit>
	<blocksmode></blocksmode>
	<blocks></blocks>
	<title_it></title_it>
	<description_it></description_it>
	<title_en></title_en>
	<title_es></title_es>
	<title_fr></title_fr>
	<title_de></title_de>
	<description_en></description_en>
	<description_es></description_es>
	<description_fr></description_fr>
	<description_de></description_de>
</fn_sections>

<fncf_news>
	<tablename>news</tablename>
	<newspp>10</newspp>
	<enablecomments>1</enablecomments>
	<guestcomment>0</guestcomment>
	<signews>1</signews>
	<guestnews>0</guestnews>
	<show_prev_next_news>1</show_prev_next_news>
	<show_same_argument_news>0</show_same_argument_news>
	<show_news_icon>1</show_news_icon>
	<htmleditornews></htmleditornews>
	<group_news>news</group_news>
	<enable_socialnetworks>0</enable_socialnetworks>
	<enable_googleplus>0</enable_googleplus>
	<enable_facebook>0</enable_facebook>
	<generate_googlesitemap>1</generate_googlesitemap>
	<enable_comments_notify>0</enable_comments_notify>
	<show_rss_icon>1</show_rss_icon>
	<show_tags>1</show_tags>
	<fb_appid>63008488243</fb_appid>
	<use_cache></use_cache>
</fncf_news>